name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run build

      - name: rsync deployments
        uses: burnett01/rsync-deployments@v5.1.0
        with:
          switches: -avzr --delete
          path: |
            app/
            public/
            index.html
          remote_path: /var/www/my-app/
          remote_host: ec2-13-48-127-58.eu-north-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Handle rsync failures
        if: ${{ failure() }}
        run: echo "rsync failed"
