name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run build

      - name: scp deployments
        run: scp -r -i ${{ secrets.SSH_PRIVATE_KEY }} ./build/* ubuntu@ec2-13-48-127-58.eu-north-1.compute.amazonaws.com:/var/www/my-app/
